event-app-master/eventManagement/eventManagement/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from eventManagement import settings
from events import views
#from django.views.decorators.cache import cache_page
#from . import views

urlpatterns = [
    path('', views.welcome),
    path('events/', include('events.urls')),
    path('admin/events/eventslabeldetails/add/',views.celebrity_mapping),
    path('admin/events/eventslabeldetails/goback/', views.goback),
    path('admin/events/eventslabeldetails/<int:id>/change/', views.update),
    path('admin/', admin.site.urls),
    #path('admin/', include('admin.urls')),
]
	
admin.site.site_header="Boutiqaat"
admin.site.site_title="Boutiqaat"
admin.site.index_title="Welcome To Boutiqaat Event Management App"

#admin.autodiscover()

event-app-master/eventManagement/events/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('celebrity_mapping/', views.celebrity_mapping, name='celebrity_mapping'),
    path('preview/', views.preview, name='preview'),
    path('getproduct/', views.getproductid, name='getproductid'),
    path('success/', views.success, name='success'),
    path('updateSuccess/', views.updateSuccess, name='updateSuccess'),
    #url(r'^select2/', include('django_select2.urls')),
]

event-app-master/eventManagement/events/models.py
from django.db import models
from django.conf import settings
#from django.contrib.auth.models import User



class Portal(models.Model):
    updated_at = models.DateTimeField(db_column='updated_at', auto_now=True)
    portal_name = models.CharField(db_column='portal_name', max_length=20)

    def __str__(self):
        return str(self.portal_name)

    class Meta:
        #managed = False
        db_table = 'portal'
        verbose_name_plural = 'Channel'


class EventType(models.Model):
    updated_at = models.DateTimeField(db_column='updated_at', auto_now=True)
    event_type = models.CharField(db_column='event_type', max_length=20)

    def __str__(self):
        return str(self.event_type)

    class Meta:
        #managed = False
        db_table = 'event_type'
        verbose_name_plural = 'Type Of Snap'


class EventClass(models.Model):
    updated_at = models.DateTimeField(db_column='updated_at', auto_now=True)
    event_class = models.CharField(db_column='event_class', max_length=20)

    def __str__(self):
        return str(self.event_class)

    class Meta:
        #managed = False
        db_table = 'event_class'
        verbose_name_plural = 'Content Type'


class MagentoCelebProd(models.Model):
    created_at = models.DateTimeField()
    celebrity_id = models.IntegerField()
    label = models.IntegerField()
    celebrity_name = models.CharField(max_length=100, blank=True, null=True)
    product_entity_id = models.IntegerField()
    sku = models.CharField(max_length=64, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'magento_celeb_prod'



class EventsHeader(models.Model):
    user_name = models.CharField(max_length=55, blank=True, null=True)
    celebrity_name = models.CharField(max_length=55, null=True)
    celebrity_id = models.PositiveIntegerField(db_column='celebrity_id', null=True)
    generic = models.CharField(max_length=55, null=True)
    event_portal = models.CharField(max_length=50, null=True)
    event_type = models.CharField(max_length=50, null=True)
    event_class = models.CharField(max_length=50, null=True)
    bq_post = models.PositiveIntegerField(db_column='bq_post')
    total_post = models.PositiveIntegerField(db_column='total_post')
    event_date = models.DateField(auto_now=False, auto_now_add=False, blank=True, null=True)
    event_time = models.TimeField(auto_now=False, auto_now_add=False, blank=True, null=True)
    created_at = models.DateTimeField(auto_now=False, auto_now_add=False, blank=True, null=True)
    updated_at = models.DateTimeField(auto_now=False, auto_now_add=False, blank=True, null=True)
    event_hours = models.PositiveIntegerField(blank=True, null=True)
    event_minutes = models.PositiveIntegerField(blank=True, null=True)
    remark = models.TextField(max_length=255,db_column='remark')

    def __str__(self):
        return str(self.user_name) + " | " + str(self.celebrity_name) + " | " + str(self.generic) + " | " + str(self.bq_post)+ " | " + str(self.total_post)+ " | " + str(self.created_at)+ " | " + str(self.updated_at)


    class Meta:
        managed = True
        db_table = 'events_header'
        verbose_name_plural = 'events'

class EventsLabelDetails(models.Model):
	user_name = models.CharField(max_length=55, blank=True, null=True)
	event = models.ForeignKey(EventsHeader, on_delete=models.CASCADE)
	labelid = models.CharField(max_length=50, null=True)
	skuid = models.CharField(max_length=50, null=True)
	created_at = models.DateTimeField(auto_now=False, auto_now_add=False, blank=True, null=True)
	updated_at = models.DateTimeField(auto_now=False, auto_now_add=False, blank=True, null=True)
	
	class Meta:
		managed = True
		db_table = 'events_label_details'
		verbose_name_plural = 'Events'

class ErpSku(models.Model):
    sku = models.CharField(db_column='SKU', primary_key=True, max_length=30)  # Field name made lowercase.
    sku_name = models.CharField(db_column='SKU_NAME', max_length=200, blank=True, null=True)  # Field name made lowercase.
    brand = models.CharField(db_column='BRAND', max_length=50, blank=True, null=True)  # Field name made lowercase.
    category1 = models.CharField(db_column='CATEGORY1', max_length=100, blank=True, null=True)  # Field name made lowercase.
    category2 = models.CharField(db_column='CATEGORY2', max_length=100, blank=True, null=True)  # Field name made lowercase.
    category3 = models.CharField(db_column='CATEGORY3', max_length=40, blank=True, null=True)  # Field name made lowercase.
    category4 = models.CharField(db_column='CATEGORY4', max_length=40, blank=True, null=True)  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'ERP_SKU'

event-app-master/eventManagement/events/views.py
from django.shortcuts import render
from django.shortcuts import render_to_response, get_object_or_404
from .models import *
import pymysql
from django.contrib.auth import get_user_model
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
import json
import pandas as pd
import datetime

#from .forms import CelebrityProductForm



def welcome(request):
    return HttpResponseRedirect(request, '/admin/')


def goback(request):
    # your code
    return HttpResponseRedirect(reverse('celebrity_mapping'))


def getproductid(request):
    celebrity = request.GET['celebrity']
    list_data = []
    print('=======Celebrity=======',celebrity)
    celebrity_id = MagentoCelebProd.objects.filter(celebrity_name=celebrity).values('celebrity_id').distinct()
    celebrity_id = celebrity_id[0]['celebrity_id']
    product_id = MagentoCelebProd.objects.filter(celebrity_id=celebrity_id).values('sku').distinct()
    list_product_id = [i for i in product_id]
    df_sku = pd.DataFrame(list_product_id)
    if df_sku.empty:
        list_id=[]
    else:
        list_id = df_sku['sku'].values.tolist()
        list_id = sorted(list_id,reverse=True)
    #print(list_id)
    list_data.append(list_id)
    label = MagentoCelebProd.objects.filter(celebrity_id=celebrity_id).values('label').distinct()
    list_label = [i for i in label]
    df_label = pd.DataFrame(list_label)
    print(df_label)
    if df_label.empty:
        lst_label=[]
    else:
        lst_label = df_label['label'].values.tolist()
        lst_label = sorted(lst_label,reverse=True)
    #
    print(lst_label)
    json_data = {'list_id':list_id,'list_label':lst_label}
    list_data.append(lst_label)
    print(list_data)
    return HttpResponse(json.dumps(list_data), content_type='application/json')   

def celebrity_mapping(request):
    user = get_user_model().objects.get(username=request.user.username)
    print(user)
    
    #celebrity = Celebrity.objects.values_list('name_e',flat=True).distinct()
    #celebrity = Celebrity.objects.all()

    celebrity = list(MagentoCelebProd.objects.values_list('celebrity_name',flat=True).distinct())
    celebrity = sorted(celebrity)
    portal = list(Portal.objects.values_list('portal_name',flat=True).distinct())
    event_type = list(EventType.objects.values_list('event_type',flat=True).distinct())
    eventclass = list(EventClass.objects.values_list('event_class',flat=True).distinct())
    context ={'user':user,'celebrity':celebrity,'eventportal':portal,'event_type':event_type,'eventclass':eventclass}

    return render(request,'celebrity_mapping/celebrity_product.html',context)


def preview(request):
    user = request.POST.get("user") 
    celebrity = request.POST.get("celebrityname",'')
    generic = request.POST.get("genericname",'') 
    productid = request.POST.getlist("productidname",'')
    labelid = request.POST.getlist("labelname",'')  
    eventportal = request.POST.get("eventportalname",'')
    eventtype = request.POST.get("eventtypename",'') 
    eventclass = request.POST.get("eventclassname",'')
    totalpost = request.POST.get("total_post",'') 
    bqpost = request.POST.get("bq_post",'')
    eventdate = request.POST.get("date",'')
    eventtime = request.POST.get("time",'')
    remark = request.POST.get("remark",'')

    celebrity_id = MagentoCelebProd.objects.filter(celebrity_name=celebrity).values('celebrity_id').distinct()
    celebrity_id = celebrity_id[0]['celebrity_id']
    print("=============Length Of Products and Labels==============")
    print(len(productid))
    print(len(labelid))
    print(user,celebrity,generic,productid,eventportal,eventtype,eventclass,totalpost,bqpost,remark,eventdate,eventtime)


    if eventportal !='null':
        eventportal=eventportal.strip('[]').replace("'",'')
    if eventtype != 'null':
        eventtype=eventtype.strip('[]').replace("'",'')
        print('========',eventtype)
    if eventclass != 'null':
        eventclass=eventclass.strip('[]').replace("'",'')
    #if generic == 'Yes':
        #productid = 'All'
    if not productid:
        productid=None
   
    if not labelid:
        labelid=None

    if productid:
        listBrandName=[]
        listCategory1=[]
        listCategory2=[]   
        for p in productid:
            brandName = ErpSku.objects.filter(sku=p).values('brand')
            if brandName:
                brandName=brandName[0]
                b=list(brandName.values())[0]
                listBrandName.append(b)
            else:
                listBrandName.append('Not Found')
            cat1 = ErpSku.objects.filter(sku=p).values('category1')
            if cat1:
                cat1=cat1[0]
                c1 = list(cat1.values())[0]
                listCategory1.append(c1)
            else:
                listCategory1.append('Not Found')
            cat2 = ErpSku.objects.filter(sku=p).values('category2')
            if cat2:
                cat2=cat2[0]
                c2 = list(cat2.values())[0]
                listCategory2.append(c2)
            else:
                listCategory2.append('Not Found')
        print("========== Printing Brand & Category For Product ID==============")
        print(listBrandName)
        print(listCategory1)
        print(listCategory2)
        #dictCelebrityPreview={'Celebrity Name':celebrity}
        dictProductIdPreview={'Product ID':productid}
        dfProductIdPreview=pd.DataFrame(dictProductIdPreview)
        dfProductIdPreview['Brand Name']=listBrandName
        dfProductIdPreview['Category1']=listCategory1
        dfProductIdPreview['Category2']=listCategory2
        dfProductIdPreview['User']=user
        dfProductIdPreview['Celebrity Name']=celebrity
        dfProductIdPreview['Generic']=generic
        dfProductIdPreview['Event Portal']=eventportal
        dfProductIdPreview['Event Type']=eventtype
        dfProductIdPreview['Event Class']=eventclass
        dfProductIdPreview['Total Post']=totalpost
        dfProductIdPreview['BQ Post']=bqpost
        dfProductIdPreview['Event Date']=eventdate
        dfProductIdPreview['Event Time']=eventtime
        dfProductIdPreview['Remark']=remark
        dfProductIdPreview['Label ID']=None
    else:
        dfProductIdPreview=pd.DataFrame()
    
    if labelid:
        listBrandName=[]
        listCategory1=[]
        listCategory2=[]
        for l in labelid:
            try:
                sku = MagentoCelebProd.objects.filter(label=l).filter(celebrity_id=celebrity_id).values('sku')[0]
            except:
                sku = None
            try:
                for k,v in sku.items():
                    s = v
            except:
                s = None
            #s = list(sku.values())[0]
            brandName = ErpSku.objects.filter(sku=s).values('brand')
            if brandName:
                brandName=brandName[0]
                b=list(brandName.values())[0]
                listBrandName.append(b)
            else:
                listBrandName.append('Not Found')
            cat1 = ErpSku.objects.filter(sku=s).values('category1')
            if cat1:
                cat1=cat1[0]
                c1 = list(cat1.values())[0]
                listCategory1.append(c1)
            else:
                listCategory1.append('Not Found')
            cat2 = ErpSku.objects.filter(sku=s).values('category2')
            if cat2:
                cat2=cat2[0]
                c2 = list(cat2.values())[0]
                listCategory2.append(c2)
            else:
                listCategory2.append('Not Found')
        print("========== Printing Brand & Category For Lable==============")
        print(listBrandName)
        print(listCategory1)
        print(listCategory2)
        dictLabelIdPreview={'Label ID':labelid}
        dfLabelIdPreview=pd.DataFrame(dictLabelIdPreview)
        dfLabelIdPreview['Brand Name']=listBrandName
        dfLabelIdPreview['Category1']=listCategory1
        dfLabelIdPreview['Category2']=listCategory2
        dfLabelIdPreview['User']=user
        dfLabelIdPreview['Celebrity Name']=celebrity
        dfLabelIdPreview['Generic']=generic
        dfLabelIdPreview['Event Portal']=eventportal
        dfLabelIdPreview['Event Type']=eventtype
        dfLabelIdPreview['Event Class']=eventclass
        dfLabelIdPreview['Total Post']=totalpost
        dfLabelIdPreview['BQ Post']=bqpost
        dfLabelIdPreview['Event Date']=eventdate
        dfLabelIdPreview['Event Time']=eventtime
        dfLabelIdPreview['Remark']=remark
        dfLabelIdPreview['Product ID']=None
    else:
        dfLabelIdPreview=pd.DataFrame()


    allProductId = MagentoCelebProd.objects.filter(celebrity_id=celebrity_id).values('sku').distinct()
    allLabelId = MagentoCelebProd.objects.filter(celebrity_id=celebrity_id).values('label').distinct()
    #print(len(allLabelId),len(labelid))
    #print(len(allProductId),len(productid))
    if productid:
        if len(allProductId)==len(productid):
            productid = 'All'
            listBrandName = 'All'
            listCategory1 = 'All'
            listCategory2 = 'All'
            dfProductIdPreview['Product ID']=productid
            dfProductIdPreview['Brand Name']=listBrandName
            dfProductIdPreview['Category1']=listCategory1
            dfProductIdPreview['Category2']=listCategory2
            dfProductIdPreview = dfProductIdPreview.iloc[:1,:]
    if labelid:
        if len(allLabelId)==len(labelid):
            labelid='All'
            listBrandName = 'All'
            listCategory1 = 'All'
            listCategory2 = 'All'
            dfLabelIdPreview['Label ID']=labelid
            dfLabelIdPreview['Brand Name']=listBrandName
            dfLabelIdPreview['Category1']=listCategory1
            dfLabelIdPreview['Category2']=listCategory2
            dfLabelIdPreview = dfLabelIdPreview.iloc[:1,:]

    dfFinal=dfProductIdPreview.append(dfLabelIdPreview, ignore_index=True)
    dfFinal=dfFinal[sorted(dfFinal.columns)]
    print(dfFinal.columns)

event-app-master/eventManagement/events/templates/celebrity_mapping/celebrity_product.html
<!DOCTYPE html>
<html lang="en-us">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>Welcome To Boutiqaat Event Management App | Boutiqaat</title>
    <!-- Bootstrap CSS -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script> 
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
    <!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous"> -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.13.1/css/bootstrap-select.min.css" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.13.1/js/bootstrap-select.min.js"></script>
    <script src="http://cdn.jsdelivr.net/timepicker.js/latest/timepicker.min.js"></script>
    <style>
    .bootstrap-select.fit-width{width: 100% !important;}
    .bootstrap-select{display: block;width: 100% !important; font-size: 1rem;line-height: 1.5;
    color: #495057;background-color: #fff;background-clip: padding-box;border: 1px solid #ced4da;
    border-radius: .25rem; transition: border-color .15s ease-in-out,box-shadow .15s ease-in-out;}
    .bootstrap-select .dropdown-menu{min-width: 100% !important;}
    </style>
    <link rel="stylesheet" type="text/css" href="/events/static/admin/css/timepicker.min.css" />
    <link rel="stylesheet" type="text/css" href="/events/static/admin/css/base.css" />
    <link rel="stylesheet" type="text/css" href="/events/static/admin/css/dashboard.css" />

    <meta name="viewport" content="user-scalable=no, width=device-width, initial-scale=1.0, maximum-scale=1.0">
    <link rel="stylesheet" type="text/css" href="/events/static/admin/css/responsive.css" />
    <meta name="robots" content="NONE,NOARCHIVE" />

</head>

<body class=" dashboard" data-admin-utc-offset="0">


<!-- Header -->
    <div id="header">
        <div id="branding">
            <h1 id="site-name"><a href="/admin/">Boutiqaat</a></h1>
        </div>
        <div id="user-tools">
            Welcome,
            <strong>{{user}}</strong>.
            <a href="/admin/">View site</a> /
            <a href="/admin/password_change/">Change password</a> /
            <a href="/admin/logout/">Log out</a>
        </div>
    </div>
    <div class="breadcrumbs">
        <a href="/admin/">Home</a>
        &rsaquo; <a href="/admin/events/">Events</a>
        &rsaquo; Events
    </div>
</body>

<body>
    <!-- Container -->
    <main class="container"><div class="row"><div class="col-8">
        <h1 class="mt-3" align="center"><strong>Add Events</strong></h1>
        <form method="POST" id="multiple_select_form" name='formname' action='/events/preview/' onsubmit="return validateForm()">
            {% csrf_token %}
            <div class="form-row mb-3">
                <label class="required col-3 text-right" for="id_user">User:</label>
                <div class="col-md-9"> 
                <select class="form-control" name="user" required id="id_user">
                    <option value="{{user}}" selected>{{user}}</option>
                </select>
                </div>
            </div>


            <div class="form-row mb-3">
                <label class="required col-md-3 text-right" for="id_user">Celebrity:</label>
                <div class="col-md-9"> 
                    <select id="cid" name="celebrityname" class="selectpicker" data-live-search="true" data-width="fit" onchange="getcelebritydata(this.value)"
                    required>
                    <!-- select all celebrity from data base and display it -->
                    <option value="">Select</option>
                    {% for c in celebrity %}
                    <option value="{{c}}">{{c}}</option>
                    {%endfor%}
                </select>
                </div>
            </div>


            <div class="form-row mb-3">
                <label class="required col-md-3 text-right" for="id_user">Generic:</label>
                <div class="col-md-9"> 
                    <select id="gid" name="genericname" class="selectpicker" data-width="fit" required>
                    <!-- select Generic from data base and display it -->
                    <option value=''>select</option>
                    <option value="Generic">Generic</option>
                    <option value="SKU Specific">SKU Specific</option>
                </select>
                </div>
            </div>
            <div class="form-row mb-3">
                <label class="required col-md-3 text-right" for="id_user">Item Label:</label>
                <div class="col-md-9">
                    <select name="labelname" id="id_label" class="selectpicker" data-live-search="true" data-actions-box="true"
                    multiple>
                    <option value="">Select</option>
                </select>
                </div>
            </div>

            <div class="form-row mb-3">
                <label class="required col-md-3 text-right" for="id_user">SKU(Optional):</label>
                <div class="col-md-9"> 
                    <select name="productidname" id="getproductid" class="selectpicker" data-live-search="true" data-actions-box="true"
                    multiple>
                    <option value="">Select</option>
                </select>
                </div>
            </div>


            <div class="form-row mb-3">
                <label class="required col-md-3 text-right" for="id_user">Channel:</label>
                <div class="col-md-9"> 
                <select id="eventportal" name="eventportalname" class="selectpicker" data-width="fit" required>
                    <!-- select all event protals from data base and display it -->
                    <option value="">Select</option>
                    {% for ep in eventportal %}
                    <option value="{{ep}}">{{ep}}</option>
                    {%endfor%}
                </select>
</div>
            </div>


            <div class="form-row mb-3">
                <label class="required col-md-3 text-right" for="id_user">Type Of Snap:</label>
                <div class="col-md-9"> <select id="eventtype" name="eventtypename" class="selectpicker" data-width="fit" required>
                    <!-- select all celebrity from data base and display it -->
                    <option value="">Select</option>
                    {% for et in event_type %}
                    <option value="{{et}}">{{et}}</option>
                    {%endfor%}
                </select>
                </div>
            </div>


            <div class="form-row mb-3">
                <label class="required col-md-3 text-right" for="id_user">Content Type:</label>
                <div class="col-md-9"> <select id="eventclass" name="eventclassname" class="selectpicker" data-width="fit" required>
                    <!-- select all eventclass from data base and display it -->
                    <option value="">Select</option>
                    {% for ec in eventclass %}
                    <option value="{{ec}}">{{ec}}</option>
                    {%endfor%}
                </select>
                </div>
            </div>


            <div class="form-row mb-3">
                <label class="required col-md-3 text-right" for="id_user">Total Posts:</label>
                <div class="col-md-9"> <input class="form-control" type="number" required name="total_post" value=""></div>
            </div>


            <div class="form-row mb-3">
                <label class="required col-md-3 text-right" for="id_user">BQ Posts:</label>
                <div class="col-md-9"> <input class="form-control" type="number" required name="bq_post" value=""></div>
            </div>


            <div class="form-row mb-3">
                <label class="required col-md-3 text-right" for="id_user">Event Date:</label>
                <div class="col-md-5"> <input class="form-control" type="date" name="date" required /></div>
                <div class="col-md-4"> <input class="form-control" type="text" id="time" name="time" placeholder="Time" required /></div>
            </div>
            


            <div class="form-row mb-3">
                <label class="required col-md-3 text-right" for="id_user">Remark:</label>
                <div class="col-md-9"> <textarea class="form-control" name="remark" id="id_remarks" cols="40" rows="4"></textarea></div>
            </div>


            <div class="form-row mb-3">
                <div class="col-md-9 offset-3">
                <input type="submit" id="submitid" name="previewname" value="Preview" class="button" />
                <input type="submit" id="myButton" name="homename" value="Home" class="button" />
                </div>
            </div>
        </form>
    </div></div>
    </main>

    <script type="text/javascript">
    document.getElementById("myButton").onclick = function () {
        location.href = '/admin/';
    };
</script>

    <script>

        function getcelebritydata() {
            var celebrity = document.getElementById("cid").value;
            console.log(celebrity)

            $.ajax(
                {
                    type: "Get",
                    url: "/events/getproduct",
                    data: { 'celebrity': celebrity },
                    success: function (result) {
                        $("#getproductid option").remove();
                        $("#id_label option").remove();
                        if (result[0].length == 0) {
                            console.log(result[0])
                            $("#getproductid").append('<option value=None>None</option>')
                        }
                        else {

                            for (var i = result[0].length - 1; i >= 0; i--) {
                                $("#getproductid").append('<option value=' + result[0][i] + '>' + result[0][i] + '</option>');
                            }
                        }

                        if (result[1].length == 0) {
                            console.log(result[1])
                            $("#id_label").append('<option value=None>None</option>')
                        }
                        else {

                            for (var i = result[1].length - 1; i >= 0; i--) {
                                $("#id_label").append('<option value=' + result[1][i] + '>' + result[1][i] + '</option>');
                            }
                        }


                        $(document).ready(function () {
                            $('.selectpicker').selectpicker();
                        });
                        $('#getproductid').addClass('form_control selectpicker');
                        $('#getproductid').attr('data-live-search', 'true');
                        $('#getproductid').selectpicker('refresh');

                        $('#id_label').addClass('form_control selectpicker');
                        $('#id_label').attr('data-live-search', 'true');
                        $('#id_label').selectpicker('refresh');

                    }


                });

        };

        var timepicker = new TimePicker(['time'], {
  lang: 'en',
  theme: 'dark'
});
timepicker.on('change', function(evt) {
  
  var value = (evt.hour || '00') + ':' + (evt.minute || '00');
  evt.element.value = value;

});

        function validateForm() {
    var x = document.forms["formname"]["productidname"].value;
    var y = document.forms["formname"]["labelname"].value;
    var total_post = document.forms["formname"]["total_post"].value;
    var totalpost = parseInt(total_post, 10);
    var bq_post = document.forms["formname"]["bq_post"].value;
    var bqpost = parseInt(bq_post, 10);
    if (x == "" && y=="") {
        alert("Please Select Either SKU Or Label");
        return false;
    }
    if (bqpost > totalpost) {
        alert("BQ Post can not be greater than total post");
        return false;
    }
    if (bqpost <=0 || totalpost <=0){
        alert("BQ Post or Total Post can not be 0 or negative !");
        return false;
    }

    var date = document.forms["formname"]["date"].value;
    var time = document.forms["formname"]["time"].value;
    var time = time.split(':')
    var h = time[0];
    var m = time[1];
    var hour = parseInt(h, 10);
    var minute = parseInt(m, 10);
    var date = new Date(date);
    date.setHours(hour,minute);
    var currentDate = new Date();

    if (date>currentDate)
    {
        alert("Please select current or past date & time !");
        return false;
    }

    var lastThreeDay = new Date();

    lastThreeDay.setDate(lastThreeDay.getDate() - 3);
    console.log(date)
    console.log(lastThreeDay)
    if (date<lastThreeDay)
    {
        alert("Please Select Maximum Last Three Day Old Data!");  
        return false;
    }


    if (m>=60)
    {
        alert("Invalid Time!");
        return false;
    }


}

</script>

</html>